In [1]:
import duckdb
con = duckdb.connect("../../data_backup/finance_data.db")

# List tables
con.sql("SHOW TABLES").df()

            name
0  afv_20_scores
1  afv_21_scores
2        tickers
3     yahoo_data

In [13]:
con.sql("""select 
        *,
        row_number() over (partition by symbol order by computed_at desc) as rn
    from afv_21_scores 
    where symbol = 'LEU'
    order by afv21 desc 
    """).df()

,symbol,afv,afv21,rp,rp21,fcf_yield,ocf_margin,min_ocf_margin,ocf_margin_volatility,sector_score,geo_score,debt_score,trend_score,vd_score,computed_at,rn
0,LEU,1.632053,2.549194,-0.667946,0.249194,0.005891,0.087466,0.02842,0.667496,1.0,0.8,1.0,0.5,-1.0,2025-11-28 15:33:12.901663,2
1,LEU,1.632052,2.549193,-0.667948,0.249193,0.005889,0.087466,0.02842,0.667496,1.0,0.8,1.0,0.5,-1.0,2025-12-29 15:34:38.279842,1
2,LEU,1.630996,2.548560,-0.669004,0.248560,0.004758,0.087466,0.02842,0.667496,1.0,0.8,1.0,0.5,-1.0,2025-10-28 04:51:56.546554,3

In [7]:
con.sql("select * from afv_21_scores where symbol like 'FCX'").df()

,symbol,afv,afv21,rp,rp21,fcf_yield,ocf_margin,min_ocf_margin,ocf_margin_volatility,sector_score,geo_score,debt_score,trend_score,vd_score,computed_at
0,FCX,-0.364568,2.111162,-1.664568,0.811162,0.042295,0.268890,0.225593,0.194455,0.5,0.8,0.5,0.0,-0.5,2025-10-28 05:43:03.833323
1,FCX,-0.376229,2.102481,-1.676229,0.802481,0.040678,0.268890,0.225593,0.194455,0.5,0.8,0.5,0.0,-0.5,2025-11-28 19:31:05.318150
2,FCX,-0.419729,2.070834,-1.719729,0.770835,0.033903,0.268890,0.225593,0.194455,0.5,0.8,0.5,0.0,-0.5,2025-12-29 19:36:06.763558
3,FCX,-1.451648,1.502631,-2.251647,0.702631,0.016047,0.238582,0.216477,0.121921,0.5,0.8,0.5,0.0,-1.0,2026-02-17 19:19:31.115904
4,FCX,-0.946298,2.005358,-2.246298,0.705358,0.017250,0.238582,0.216477,0.121921,0.5,0.8,0.5,0.0,-0.5,2026-03-18 19:19:12.856635
5,FCX,-1.453200,1.501843,-2.253200,0.701843,0.015691,0.238582,0.216477,0.121921,0.5,0.8,0.5,0.0,-1.0,2026-05-25 08:49:11.490026

In [3]:
con.sql("delete from afv_21_scores where round(afv21,0) = -1000").df()

AttributeError: 'NoneType' object has no attribute 'df'

In [30]:
con.sql("select * from afv_21_scores where symbol = '1AAL.MI'").df()

,symbol,afv,afv21,rp,rp21,fcf_yield,ocf_margin,min_ocf_margin,ocf_margin_volatility,sector_score,geo_score,debt_score,trend_score,vd_score,computed_at
0,1AAL.MI,-0.621680,-0.082535,-0.421680,0.117465,0.081517,0.053362,0.023559,0.449029,-1.0,0.8,0.0,0.0,0.0,2025-10-28 03:00:07.949445
1,1AAL.MI,-0.687123,-0.098032,-0.487123,0.101968,0.071592,0.053362,0.023559,0.449029,-1.0,0.8,0.0,0.0,0.0,2025-11-28 03:00:36.571711
2,1AAL.MI,-0.731990,-0.108083,-0.531990,0.091917,0.063041,0.053362,0.023559,0.449029,-1.0,0.8,0.0,0.0,0.0,2025-12-29 03:00:27.212223

In [52]:
con.sql("select current_timestamp + INTERVAL 1 MONTH").df()

  (current_timestamp + to_months(CAST(trunc(CAST(1 AS DOUBLE)) AS INTEGER)))
0                   2025-10-19 14:12:36.751380+03:00

In [40]:
con.sql("insert into yahoo_data (symbol, dataset, data, ts) values ('test', 'test', '{}')")

BinderException: Binder Error: Column name/value mismatch for insert on yahoo_data: expected 4 columns but 3 values were supplied

In [9]:
con.sql("select *  from tickers where mic = 'FCX'").df()

ConnectionException: Connection Error: Connection already closed!

In [171]:
con.sql("drop table afv_20_scores").df()

AttributeError: 'NoneType' object has no attribute 'df'

In [159]:
con.sql("delete from afv_20_scores").df()

AttributeError: 'NoneType' object has no attribute 'df'

In [31]:
con.close()