In [20]:
import duckdb
con = duckdb.connect("../../data_backup/finance_data.db")

# List tables
con.sql("SHOW TABLES").df()

                 name
0       afv_20_scores
1       afv_21_scores
2            holdings
3  technical_analysis
4             tickers
5          yahoo_data

In [13]:
con.sql("""select 
        *,
        row_number() over (partition by symbol order by computed_at desc) as rn
    from afv_21_scores 
    where symbol = 'LEU'
    order by afv21 desc 
    """).df()

,symbol,afv,afv21,rp,rp21,fcf_yield,ocf_margin,min_ocf_margin,ocf_margin_volatility,sector_score,geo_score,debt_score,trend_score,vd_score,computed_at,rn
0,LEU,1.632053,2.549194,-0.667946,0.249194,0.005891,0.087466,0.02842,0.667496,1.0,0.8,1.0,0.5,-1.0,2025-11-28 15:33:12.901663,2
1,LEU,1.632052,2.549193,-0.667948,0.249193,0.005889,0.087466,0.02842,0.667496,1.0,0.8,1.0,0.5,-1.0,2025-12-29 15:34:38.279842,1
2,LEU,1.630996,2.548560,-0.669004,0.248560,0.004758,0.087466,0.02842,0.667496,1.0,0.8,1.0,0.5,-1.0,2025-10-28 04:51:56.546554,3

In [21]:
con.sql("select * from holdings").df()

,fetched_at,yahoo_symbol,symbol,description,isin,exchange,currency,position,mark_price,pos_value,cost_basis
0,2026-07-01 13:18:20.258874,CA.PA,CA,CARREFOUR SA,FR0000120172,SBF,EUR,80.0,16.250000,1300.000000,1003.000000
1,2026-07-01 13:18:20.259492,SOP.PA,SOP,SOPRA STERIA GROUP,FR0000050809,SBF,EUR,30.0,139.600006,4188.000000,4362.000000
2,2026-07-01 13:18:20.259890,SSABBH.HE,SSABBH,SSAB AB - B SHARES,SE0000120669,HEX,EUR,200.0,8.100000,1620.000000,969.000000
3,2026-07-01 13:18:20.260249,CNQ,CNQ,CANADIAN NATURAL RESOURCES,CA1363851017,NYSE,USD,50.0,39.500000,1975.000000,1523.251099
4,2026-07-01 13:18:20.260562,EQNR,EQNR,EQUINOR ASA-SPON ADR,US29446M1027,NYSE,USD,50.0,31.400000,1570.000000,1274.966064
5,2026-07-01 13:18:20.260859,FCX,FCX,FREEPORT-MCMORAN INC,US35671D8570,NYSE,USD,100.0,62.889999,6289.000000,5367.000000
6,2026-07-01 13:18:20.261120,LPG,LPG,DORIAN LPG LTD,MHY2106R1100,NYSE,USD,21.0,34.779999,730.380005,524.109985
7,2026-07-01 13:18:20.261358,SHEL,SHEL,SHELL PLC-ADR,US7802593050,NYSE,USD,100.0,77.540001,7754.000000,7511.000000
8,2026-07-01 13:18:20.261796,SM,SM,SM ENERGY CO,US78454L1008,NYSE,USD,245.0,26.100000,6394.500000,5075.910156

In [3]:
con.sql("delete from afv_21_scores where round(afv21,0) = -1000").df()

AttributeError: 'NoneType' object has no attribute 'df'

In [18]:
con.sql("select * from afv_21_scores where symbol = 'CA.PA'").df()

,symbol,afv,afv21,rp,rp21,fcf_yield,ocf_margin,min_ocf_margin,ocf_margin_volatility,sector_score,geo_score,debt_score,trend_score,vd_score,computed_at
0,CA.PA,6.162114,4.132749,4.662114,2.632749,0.249383,0.051171,0.048127,0.053348,0.5,1.0,1.0,-0.5,-0.5,2025-10-28 03:19:27.201384
1,CA.PA,6.204795,4.143759,4.704795,2.643759,0.254097,0.051171,0.048127,0.053348,0.5,1.0,1.0,-0.5,-0.5,2025-11-28 05:22:56.438788
2,CA.PA,6.032529,4.097653,4.532529,2.597653,0.237907,0.051171,0.048127,0.053348,0.5,1.0,1.0,-0.5,-0.5,2025-12-29 05:23:26.752398
3,CA.PA,5.663942,3.987148,4.163942,2.487148,0.216592,0.051171,0.048127,0.053348,0.5,1.0,1.0,-0.5,-0.5,2026-02-17 05:19:38.957247
4,CA.PA,5.750228,4.011675,4.250228,2.511675,0.220687,0.050714,0.046987,0.062819,0.5,1.0,0.0,-0.5,0.5,2026-03-18 05:22:05.416848
5,CA.PA,6.362611,4.885431,3.862611,2.385431,0.204662,0.050714,0.046987,0.062819,0.5,1.0,1.0,-0.5,0.5,2026-05-24 16:06:27.778934
6,CA.PA,6.592437,4.961728,4.092437,2.461728,0.213468,0.050714,0.046987,0.062819,0.5,1.0,1.0,-0.5,0.5,2026-06-27 18:19:53.232649

In [52]:
con.sql("select current_timestamp + INTERVAL 1 MONTH").df()

  (current_timestamp + to_months(CAST(trunc(CAST(1 AS DOUBLE)) AS INTEGER)))
0                   2025-10-19 14:12:36.751380+03:00

In [40]:
con.sql("insert into yahoo_data (symbol, dataset, data, ts) values ('test', 'test', '{}')")

BinderException: Binder Error: Column name/value mismatch for insert on yahoo_data: expected 4 columns but 3 values were supplied

In [9]:
con.sql("select *  from tickers where mic = 'FCX'").df()

ConnectionException: Connection Error: Connection already closed!

In [171]:
con.sql("drop table afv_20_scores").df()

AttributeError: 'NoneType' object has no attribute 'df'

In [159]:
con.sql("delete from afv_20_scores").df()

AttributeError: 'NoneType' object has no attribute 'df'

In [22]:
con.close()